base_url = "https://carbon-creations.github.io/"
title = "carbons insanity"
theme = "radion"
description = "An assortment of my ramblings and random adventures."
generate_feeds = true

taxonomies = [
    # You can enable/disable RSS
    {name = "categories", feed = true},
    {name = "tags", feed = true},
 ]

# When set to "true", the Sass files in the `sass` directory in the site root are compiled.
# Sass files in theme directories are always compiled.
compile_sass = true

# When set to "true", a search index is built from the pages and section
# content for `default_language`.
build_search_index = true

[markdown]
# Whether to do syntax highlighting
# Theme can be customized by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true
highlight_theme = "one-dark"

insert_anchor_links = "heading"

[search]
# Wether to produce the search index as a javascript file or as a JSON file
# Accepted values:
# - "elasticlunr_javascript", "elasticlunr_json"
# - "fuse_javascript", "fuse_json"
index_format = "elasticlunr_json"

[extra]
# Put all your custom variables here
radion_title = "carbons insanity"
author = "Carbon"
github = "https://github.com/carbon-creations"
radion_menu = [
    {url = "$BASE_URL/", name = "Home"},
    {url = "$BASE_URL/categories", name = "Categories"},
    {url = "$BASE_URL/tags", name = "Tags"},
]


# Nicer codeblocks with copy to clipboard
codeblock = true

# Enable MathJax rendering support
latex = true

# Enable search bar
enable_search = true

# Light/Dark Mode set
theme = "toggle" # options: {light, dark, auto, toggle}

# Comment sections
comments = true
giscus_repo = "carbon-creations/carbon-creations.github.io"
giscus_repo_id = "R_kgDOPfjhFw"
giscus_data_category_id = "DIC_kwDOPfjhF84CuR8-"